/**
    account_user
 */
create table $$$raw_schema$$$.account_user
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status      EnumStatus,
    username    varchar(255) not null unique,
    password    varchar(255) not null,
    name        varchar(255) not null,
    surname     varchar(255) not null,
    email       varchar(255),
    version     bigint,
    create_date timestamp(6) with time zone,
    update_date timestamp(6) with time zone
);
/**
    account_user_roles
 */
create table $$$raw_schema$$$.account_user_roles
(
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);
/**
    account_role
 */
create table $$$raw_schema$$$.account_role
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status      EnumStatus,
    code        varchar(100) not null unique,
    description varchar(1000),
    name        varchar(255) not null,
    version     bigint,
    create_date timestamp(6) with time zone,
    update_date timestamp(6) with time zone
);
/**
    account_role_grant  ,
 */
create table $$$raw_schema$$$.account_role_grant
(
    grant_id bigint not null,
    role_id  bigint not null,
    primary key (grant_id, role_id)
);
/**
    account_grant
 */
create table $$$raw_schema$$$.account_grant
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status      EnumStatus,
    code        varchar(100) not null unique,
    name        varchar(255) not null,
    permission  varchar(255),
    version     bigint,
    create_date timestamp(6) with time zone,
    update_date timestamp(6) with time zone
);
/**
    error_logs
 */
create table $$$raw_schema$$$.error_logs
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp   TIMESTAMP NOT NULL,
    level       VARCHAR(50),
    logger      VARCHAR(255),
    message     TEXT,
    method      VARCHAR(200),
    line        VARCHAR(50),
    exception   TEXT,
    status      EnumStatus,
    version     bigint,
    update_date timestamp(6) with time zone,
    create_date timestamp(6) with time zone
);
